//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consumidor.Matematica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://udb.edu.sv/servicio/", ConfigurationName="Matematica.MatematicasSoap")]
    public interface MatematicasSoap {
        
        // CODEGEN: Generating message contract since element name SumarResult from namespace http://udb.edu.sv/servicio/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Sumar", ReplyAction="*")]
        Consumidor.Matematica.SumarResponse Sumar(Consumidor.Matematica.SumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Matematica.SumarResponse> SumarAsync(Consumidor.Matematica.SumarRequest request);
        
        // CODEGEN: Generating message contract since element name RestarResult from namespace http://udb.edu.sv/servicio/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Restar", ReplyAction="*")]
        Consumidor.Matematica.RestarResponse Restar(Consumidor.Matematica.RestarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Restar", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Matematica.RestarResponse> RestarAsync(Consumidor.Matematica.RestarRequest request);
        
        // CODEGEN: Generating message contract since element name MultiplicarResult from namespace http://udb.edu.sv/servicio/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Multiplicar", ReplyAction="*")]
        Consumidor.Matematica.MultiplicarResponse Multiplicar(Consumidor.Matematica.MultiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Multiplicar", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Matematica.MultiplicarResponse> MultiplicarAsync(Consumidor.Matematica.MultiplicarRequest request);
        
        // CODEGEN: Generating message contract since element name DividirResult from namespace http://udb.edu.sv/servicio/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Dividir", ReplyAction="*")]
        Consumidor.Matematica.DividirResponse Dividir(Consumidor.Matematica.DividirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://udb.edu.sv/servicio/Dividir", ReplyAction="*")]
        System.Threading.Tasks.Task<Consumidor.Matematica.DividirResponse> DividirAsync(Consumidor.Matematica.DividirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sumar", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.SumarRequestBody Body;
        
        public SumarRequest() {
        }
        
        public SumarRequest(Consumidor.Matematica.SumarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class SumarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double number2;
        
        public SumarRequestBody() {
        }
        
        public SumarRequestBody(double number1, double number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SumarResponse", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.SumarResponseBody Body;
        
        public SumarResponse() {
        }
        
        public SumarResponse(Consumidor.Matematica.SumarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class SumarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SumarResult;
        
        public SumarResponseBody() {
        }
        
        public SumarResponseBody(string SumarResult) {
            this.SumarResult = SumarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Restar", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.RestarRequestBody Body;
        
        public RestarRequest() {
        }
        
        public RestarRequest(Consumidor.Matematica.RestarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class RestarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double number2;
        
        public RestarRequestBody() {
        }
        
        public RestarRequestBody(double number1, double number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestarResponse", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.RestarResponseBody Body;
        
        public RestarResponse() {
        }
        
        public RestarResponse(Consumidor.Matematica.RestarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class RestarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RestarResult;
        
        public RestarResponseBody() {
        }
        
        public RestarResponseBody(string RestarResult) {
            this.RestarResult = RestarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Multiplicar", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.MultiplicarRequestBody Body;
        
        public MultiplicarRequest() {
        }
        
        public MultiplicarRequest(Consumidor.Matematica.MultiplicarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class MultiplicarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double number2;
        
        public MultiplicarRequestBody() {
        }
        
        public MultiplicarRequestBody(double number1, double number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiplicarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiplicarResponse", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.MultiplicarResponseBody Body;
        
        public MultiplicarResponse() {
        }
        
        public MultiplicarResponse(Consumidor.Matematica.MultiplicarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class MultiplicarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MultiplicarResult;
        
        public MultiplicarResponseBody() {
        }
        
        public MultiplicarResponseBody(string MultiplicarResult) {
            this.MultiplicarResult = MultiplicarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DividirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dividir", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.DividirRequestBody Body;
        
        public DividirRequest() {
        }
        
        public DividirRequest(Consumidor.Matematica.DividirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class DividirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double number1;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double number2;
        
        public DividirRequestBody() {
        }
        
        public DividirRequestBody(double number1, double number2) {
            this.number1 = number1;
            this.number2 = number2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DividirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DividirResponse", Namespace="http://udb.edu.sv/servicio/", Order=0)]
        public Consumidor.Matematica.DividirResponseBody Body;
        
        public DividirResponse() {
        }
        
        public DividirResponse(Consumidor.Matematica.DividirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://udb.edu.sv/servicio/")]
    public partial class DividirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DividirResult;
        
        public DividirResponseBody() {
        }
        
        public DividirResponseBody(string DividirResult) {
            this.DividirResult = DividirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MatematicasSoapChannel : Consumidor.Matematica.MatematicasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatematicasSoapClient : System.ServiceModel.ClientBase<Consumidor.Matematica.MatematicasSoap>, Consumidor.Matematica.MatematicasSoap {
        
        public MatematicasSoapClient() {
        }
        
        public MatematicasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatematicasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatematicasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatematicasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Matematica.SumarResponse Consumidor.Matematica.MatematicasSoap.Sumar(Consumidor.Matematica.SumarRequest request) {
            return base.Channel.Sumar(request);
        }
        
        public string Sumar(double number1, double number2) {
            Consumidor.Matematica.SumarRequest inValue = new Consumidor.Matematica.SumarRequest();
            inValue.Body = new Consumidor.Matematica.SumarRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            Consumidor.Matematica.SumarResponse retVal = ((Consumidor.Matematica.MatematicasSoap)(this)).Sumar(inValue);
            return retVal.Body.SumarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Matematica.SumarResponse> Consumidor.Matematica.MatematicasSoap.SumarAsync(Consumidor.Matematica.SumarRequest request) {
            return base.Channel.SumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Matematica.SumarResponse> SumarAsync(double number1, double number2) {
            Consumidor.Matematica.SumarRequest inValue = new Consumidor.Matematica.SumarRequest();
            inValue.Body = new Consumidor.Matematica.SumarRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((Consumidor.Matematica.MatematicasSoap)(this)).SumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Matematica.RestarResponse Consumidor.Matematica.MatematicasSoap.Restar(Consumidor.Matematica.RestarRequest request) {
            return base.Channel.Restar(request);
        }
        
        public string Restar(double number1, double number2) {
            Consumidor.Matematica.RestarRequest inValue = new Consumidor.Matematica.RestarRequest();
            inValue.Body = new Consumidor.Matematica.RestarRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            Consumidor.Matematica.RestarResponse retVal = ((Consumidor.Matematica.MatematicasSoap)(this)).Restar(inValue);
            return retVal.Body.RestarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Matematica.RestarResponse> Consumidor.Matematica.MatematicasSoap.RestarAsync(Consumidor.Matematica.RestarRequest request) {
            return base.Channel.RestarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Matematica.RestarResponse> RestarAsync(double number1, double number2) {
            Consumidor.Matematica.RestarRequest inValue = new Consumidor.Matematica.RestarRequest();
            inValue.Body = new Consumidor.Matematica.RestarRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((Consumidor.Matematica.MatematicasSoap)(this)).RestarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Matematica.MultiplicarResponse Consumidor.Matematica.MatematicasSoap.Multiplicar(Consumidor.Matematica.MultiplicarRequest request) {
            return base.Channel.Multiplicar(request);
        }
        
        public string Multiplicar(double number1, double number2) {
            Consumidor.Matematica.MultiplicarRequest inValue = new Consumidor.Matematica.MultiplicarRequest();
            inValue.Body = new Consumidor.Matematica.MultiplicarRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            Consumidor.Matematica.MultiplicarResponse retVal = ((Consumidor.Matematica.MatematicasSoap)(this)).Multiplicar(inValue);
            return retVal.Body.MultiplicarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Matematica.MultiplicarResponse> Consumidor.Matematica.MatematicasSoap.MultiplicarAsync(Consumidor.Matematica.MultiplicarRequest request) {
            return base.Channel.MultiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Matematica.MultiplicarResponse> MultiplicarAsync(double number1, double number2) {
            Consumidor.Matematica.MultiplicarRequest inValue = new Consumidor.Matematica.MultiplicarRequest();
            inValue.Body = new Consumidor.Matematica.MultiplicarRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((Consumidor.Matematica.MatematicasSoap)(this)).MultiplicarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Consumidor.Matematica.DividirResponse Consumidor.Matematica.MatematicasSoap.Dividir(Consumidor.Matematica.DividirRequest request) {
            return base.Channel.Dividir(request);
        }
        
        public string Dividir(double number1, double number2) {
            Consumidor.Matematica.DividirRequest inValue = new Consumidor.Matematica.DividirRequest();
            inValue.Body = new Consumidor.Matematica.DividirRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            Consumidor.Matematica.DividirResponse retVal = ((Consumidor.Matematica.MatematicasSoap)(this)).Dividir(inValue);
            return retVal.Body.DividirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Consumidor.Matematica.DividirResponse> Consumidor.Matematica.MatematicasSoap.DividirAsync(Consumidor.Matematica.DividirRequest request) {
            return base.Channel.DividirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Consumidor.Matematica.DividirResponse> DividirAsync(double number1, double number2) {
            Consumidor.Matematica.DividirRequest inValue = new Consumidor.Matematica.DividirRequest();
            inValue.Body = new Consumidor.Matematica.DividirRequestBody();
            inValue.Body.number1 = number1;
            inValue.Body.number2 = number2;
            return ((Consumidor.Matematica.MatematicasSoap)(this)).DividirAsync(inValue);
        }
    }
}
